$(document).ready(function(){
        $("#btnETP").click(function(){
            $("#tabelaETP").slideToggle('fast');
            if($('button#btnETP').text() == "-")
            {
                $('button#btnETP').text("+");
            }
            else
            {
                $('button#btnETP').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnRegistroEstoque").click(function(){
        $("#tabelaRegistroEstoque").slideToggle('fast');
            if($('button#btnRegistroEstoque').text() == "-")
            {
                $('button#btnRegistroEstoque').text("+");
            }
            else
            {
                $('button#btnRegistroEstoque').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnTAT").click(function(){
        $("#tabelaTAT").slideToggle('fast');
            if($('button#btnTAT').text() == "-")
            {
                $('button#btnTAT').text("+");
            }
            else
            {
                $('button#btnTATA').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnAeracao").click(function(){
        $("#tabelaAeracao").slideToggle('fast');
            if($('button#btnAeracao').text() == "-")
            {
                $('button#btnAeracao').text("+");
            }
            else
            {
                $('button#btnAeracao').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnExpurgo").click(function(){
        $("#tabelaExpurgo").slideToggle('fast');
            if($('button#btnExpurgo').text() == "-")
            {
                $('button#btnExpurgo').text("+");
            }
            else
            {
                $('button#btnExpurgo').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnPulverizacao").click(function(){
        $("#tabelaPulverizacao").slideToggle('fast');
            if($('button#btnPulverizacao').text() == "-")
            {
                $('button#btnPulverizacao').text("+");
            }
            else
            {
                $('button#btnPulverizacao').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnNebulizacao").click(function(){
        $("#tabelaNebulizacao").slideToggle('fast');
            if($('button#btnNebulizacao').text() == "-")
            {
                $('button#btnNebulizacao').text("+");
            }
            else
            {
                $('button#btnNebulizacao').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnRastelagem").click(function(){
        $("#tabelaRastelagem").slideToggle('fast');
            if($('button#btnRastelagem').text() == "-")
            {
                $('button#btnRastelagem').text("+");
            }
            else
            {
                $('button#btnRastelagem').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnRemaquinacao").click(function(){
        $("#tabelaRemaquinacao").slideToggle('fast');
            if($('button#btnRemaquinacao').text() == "-")
            {
                $('button#btnRemaquinacao').text("+");
            }
            else
            {
                $('button#btnRemaquinacao').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnTermometria").click(function(){
        $("#tabelaTermometria").slideToggle('fast');
            if($('button#btnTermometria').text() == "-")
            {
                $('button#btnTermometria').text("+");
            }
            else
            {
                $('button#btnTermometria').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnTransilagem").click(function(){
        $("#tabelaTransilagem").slideToggle('fast');
            if($('button#btnTransilagem').text() == "-")
            {
                $('button#btnTransilagem').text("+");
            }
            else
            {
                $('button#btnTransilagem').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnTratamento").click(function(){
        $("#tabelaTratamento").slideToggle('fast');
            if($('button#btnTratamento').text() == "-")
            {
                $('button#btnTratamento').text("+");
            }
            else
            {
                $('button#btnTratamento').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnSondagemPadrao").click(function(){
        $("#tabelaSondagemPadrao").slideToggle('fast');
            if($('button#btnSondagemPadrao').text() == "-")
            {
                $('button#btnSondagemPadrao').text("+");
            }
            else
            {
                $('button#btnSondagemPadrao').text("-");
            }
        });
    });
    $(document).ready(function(){
    $("#btnSondagemTermometria").click(function(){
        $("#tabelaSondagemTermometria").slideToggle('fast');
            if($('button#btnSondagemTermometria').text() == "-")
            {
                $('button#btnSondagemTermometria').text("+");
            }
            else
            {
                $('button#btnSondagemTermometria').text("-");
            }
        });
    });